spring.application.name=nova-nest-backend
# Default to local
spring.profiles.active=local

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Explicitly set MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Local Database Settings
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sohail
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080

# Common Secrets (Consider moving sensitive info to environment variables eventually)
app.jwt.secret=NovaNestSecretKeyForJwtAuthentication123456789
app.jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=isksohail7@gmail.com
spring.mail.password=hssbzarhlpvahojg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key.id=rzp_test_TK6J9KYJRj12mg
razorpay.key.secret=gOOS6uGdOGTZU7KPvVuT02ML
